[phases.build]
cmds = [
  'npm ci --include=dev',
  'if [ -n "$DATABASE_URL" ]; then cp prisma/schema.production.prisma prisma/schema.prisma; fi',
  'npx prisma generate',
  'npm run build'
]

[phases.start]
cmd = 'if [ -n "$DATABASE_URL" ]; then npx prisma db push --accept-data-loss; fi && npm start'