# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbb5a44b5fc8b588a7198a726ec321ab"
name = "marble-hills-subscription"
handle = "marble-hills-subscription"
application_url = "https://wing-twin-sensitive-players.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders"

[auth]
redirect_urls = ["https://wing-twin-sensitive-players.trycloudflare.com/auth/callback", "https://wing-twin-sensitive-players.trycloudflare.com/auth/shopify/callback", "https://wing-twin-sensitive-players.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://wing-twin-sensitive-players.trycloudflare.com/apps"
subpath = "subscription"
prefix = "apps"
